[[docs]]
  name = "Installation"
  weight = 10
  identifier = "installation"
  url = "/docs/installation/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"



[[main]]
  name = "Docs"
  url = "/docs/installation/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20





# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
